### ISSUE TITLE
#Enhancement Need this extension on Firefox too!

### ISSUE THREAD

**Issue by Vincent-Bouton** [kkurczewski/blur-youtube-thumbnails#1]
Would be great if the extension would be on both Chrome and Firefox.

**Comment by kkurczewski** [comment]
I have good and bad news.

Good news is that I added extension as **experimental version** to Firefox store [here](https://addons.mozilla.org/pl/firefox/addon/blurred-thumbnails/).

Bad news is that Firefox is missing support for [:has selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility) which I use through code. Although MDN docs says it is supported via custom flag in fact [it isn't](https://stackoverflow.com/questions/73936048/how-do-you-enable-has-selector-on-firefox#comment133204727_73936256).

I already had to adjust Manifest V3 (which was meant to be cross-browser compatible) so missing selector support is probably tip of iceberg. That being said this issue blocks any further testing so Firefox support will be frozen for now.

**Comment by kkurczewski** [comment]
Hi, as Firefox added missing support I was able to release extension to Firefox store:
https://addons.mozilla.org/pl/firefox/addon/blurred-thumbnails/

From what I check you need to manually tick page permissions and then you have to fill tags under **preferences** tab:
![image](https://github.com/kkurczewski/blur-youtube-thumbnails/assets/25885028/93549d21-e247-4828-a31d-33352c97edcd)

Moreover, this extension uses background worker/script hence you need to make sure that browser has it enabled.

---

Here is how it looks:
![image](https://github.com/kkurczewski/blur-youtube-thumbnails/assets/25885028/43eaeb9a-0345-476d-82dd-15c964966608)
